application:
  name: ee.smit
  type: app

environment:

  manchester:
    address: "14 Bury New Rd, Manchester"
    available: true
    api:
      endpoint: "http://localhost:9004"
      tirechangepath: "/api/v2/tire-change-times"

  london:
    address: "1A Gunton Rd, London"
    available: true
    api:
      endpoint: "http://localhost:9003"
      tirechangepath: "/api/v1/tire-change-times"