version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPRING_CONFIG_LOCATION=file:/config/application.yml
    ports:
      - "9006:8080"
  frontend:
    build:
      context: .
      dockerfile: tirefrontend/Dockerfile
    ports:
      - "9005:80"